FROM golang:1.25 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY ./src ./src
RUN CGO_ENABLED=0 GOOS=linux go build -o src/server ./src

FROM gcr.io/distroless/base-debian12

WORKDIR /app

COPY --from=builder /app/src/server /app/server

EXPOSE 8080

CMD ["/app/server"]
